export const API_KEY = 'b6d2e3a714047dd33bb390fcbc6cdc5f';
export const LOCALIZATION = {
  search: ['Поиск', 'Search'],
  popular: ['Популярные фильмы', 'Popular Movies'],
  top_rated: ['Лучшие фильмы', 'Top Rated Movies'],
  showMore: ['Показать больше', 'Show more'],
  favorites: ['Избранное', 'Favorites'],
  searchMovies: ['Поиск фильмов...', 'Search movies...'],
  releaseDate: ['Дата выхода', 'Release date'],
  tagline: ['Слоган', 'Tagline'],
  description: ['Описание', 'Description'],
  genres: ['Жанры', 'Genres'],
  recommendations: ['Рекомендации', 'Recomendations'],
  page: ['Страница', 'Page'],
  of: ['из', 'of'],
  addToFavorites: ['Добавить в избранные', 'Add to favorites'],
  removeFromFavorites: ['Убрать из избранного', 'Remove from favorites'],
  cast: ['Актёрский состав', 'Cast'],
  showAllCast: ['Показать весь список', 'Show all cast'],
  name: ['Имя', 'Name'],
  birthday: ['День рождения', 'Birthday'],
  deathday: ['День смерти', 'Deathday'],
  placeOfBirth: ['Место рождения', 'Place of birth'],
  biography: ['Биография', 'Biography'],
  creditsByPerson: ['Фильмы с участием', 'Movies featuring'],
  movieImages: ['Изображения фильма', 'Movie images']
};
